### ISSUE TITLE
generate_dataset.py is not working

### ISSUE THREAD

**Issue by AFAgarap** [velebit-ai/COVID-Next-Pytorch#1]
First, the help argument for `generate_dataset.py` does not work. 

Second, it is converting the `.dcm` files from the Kaggle dataset, but it's not doing anything for the `ieee8023/covid-chestxray-dataset`. The following is the output of the said module,

```shell
$ python generate_dataset.py --covid-dir covid-chestxray-dataset --kaggle-data rsna-pneumonia-detection-challenge --save-path COVIDx
INFO:__main__:Data distribution from covid-chestxray-dataset:
INFO:__main__:{'normal': 0, 'pneumonia': 0, 'COVID-19': 0}
INFO:__main__:test count: {'normal': 0, 'pneumonia': 0, 'COVID-19': 0}
INFO:__main__:train count: {'normal': 0, 'pneumonia': 0, 'COVID-19': 0}
INFO:__main__:Preparing Kaggle dataset...
INFO:__main__:Category: normal, N Test examples: 885
```

**Comment by iborko** [comment]
Yes, there was a problem. It did nothing because the `covid-chestxray` dataset slightly changed the format of "findings" strings in the metadata file. It is fixed now.

**Comment by AFAgarap** [comment]
Thanks!
