### ISSUE TITLE
about COVID-Net model

### ISSUE THREAD

**Issue by jiejiangd** [velebit-ai/COVID-Next-Pytorch#4]
I take the liberty to ask if you can provide the training code of the baseline COVID-Net for the COVID-NeXt model.

**Comment by mfernezir** [comment]
Hi @jiejiangd! Sorry for the late reply. We are currently all booked on other projects, so we are not free at the moment for additional improvements in this repository. However, we would gladly review and add a pull request for this enhancement.

Best regards,

Mladen
